# Generated by Django 3.2 on 2022-05-20 14:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 20, 14, 57, 38, 463438, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
