# Generated by Django 3.2 on 2022-07-08 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Programme',
        ),
    ]
